apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
    service: notification-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "actuator/prometheus"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8086
    name: http
  selector:
    app: notification-service
