apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - service-monitor.yaml

commonLabels:
  app: api-gateway
  tier: backend

images:
  - name: api-gateway
    newName: ${{CONTAINER_REGISTRY}}/${{GITHUB_REPOSITORY_OWNER}}/api-gateway
    newTag: latest
